#include "bsp_io.h"
#include "main.h" // Includes the I2C handle created by CubeMX

// This is the I2C handle generated by STM32CubeIDE.
// It is declared as an 'extern' variable in main.h.
extern I2C_HandleTypeDef hi2c1;

/**
  * @brief  Initializes the low-level I/O.
  * @note   This function is typically empty when using CubeMX, as the
  * initialization is handled by MX_I2C1_Init() in main.c.
  * @retval None
  */
void COMPASSACCELERO_IO_Init(void)
{
    // The I2C peripheral is initialized in main.c
}

/**
  * @brief  Writes a single byte to a register of the LSM303AGR sensor.
  * @param  DeviceAddr: The 8-bit I2C address of the device (shifted).
  * @param  RegisterAddr: The register address to write to.
  * @param  Value: The data byte to write.
  * @retval None
  */
void COMPASSACCELERO_IO_Write(uint16_t DeviceAddr, uint8_t RegisterAddr, uint8_t Value)
{
    // Write one byte to the specified register.
    // The HAL function handles the I2C start, address, register, and stop conditions.
    HAL_I2C_Mem_Write(&hi2c1, DeviceAddr, RegisterAddr, I2C_MEMADD_SIZE_8BIT, &Value, 1, 1000);
}

/**
  * @brief  Reads a single byte from a register of the LSM303AGR sensor.
  * @param  DeviceAddr: The 8-bit I2C address of the device (shifted).
  * @param  RegisterAddr: The register address to read from.
  * @retval The data byte read from the register.
  */
uint8_t COMPASSACCELERO_IO_Read(uint16_t DeviceAddr, uint8_t RegisterAddr)
{
    uint8_t value = 0;
    // Read one byte from the specified register.
    // The HAL function handles the I2C start, address, register, and stop conditions.
    HAL_I2C_Mem_Read(&hi2c1, DeviceAddr, RegisterAddr, I2C_MEMADD_SIZE_8BIT, &value, 1, 1000);
    return value;
}

/**
  * @brief  Initializes I/O for interrupt functionality.
  * @note   This is for configuring GPIOs as external interrupt lines.
  * @retval None
  */
void COMPASSACCELERO_IO_ITConfig(void)
{
    // In your CubeMX configuration, you need to set up the pins
    // connected to INT_MAG and INT_ACC as External Interrupts (EXTI).
    // This function will be called by the driver but can be left empty
    // since CubeMX generates the necessary code in the HAL layer.
}
